-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB INNER JOIN USED_GOODS_USER UGU 
ON UGB.WRITER_ID = UGU.USER_ID
WHERE STATUS = 'DONE'
GROUP BY UGB.WRITER_ID, UGB.STATUS
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;