# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE CONV(SKILL_CODE, 10, 2) LIKE '%1__________' OR CONV(SKILL_CODE, 10, 2) LIKE '%1________'
# ORDER BY ID ASC;

select distinct ID, EMAIL, FIRST_NAME, LAST_NAME
from DEVELOPERS
join SKILLCODES on SKILLCODES.CODE & DEVELOPERS.SKILL_CODE != 0
where SKILLCODES.NAME in ('C#','Python')
order by id