SELECT FI.ID, FNI.FISH_NAME, FM.MAX AS LENGTH
FROM (
SELECT MAX(LENGTH) AS MAX, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
) AS FM INNER JOIN FISH_INFO FI ON FM.MAX = FI.LENGTH AND FM.FISH_TYPE = FI.FISH_TYPE 
INNER JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID ASC