SELECT BI.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK BI JOIN BOOK_SALES BS on BI.BOOK_ID = BS.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BI.CATEGORY
ORDER BY BI.CATEGORY ASC;